#!/usr/bin/bash

# Build rule
filename="$1"
figlet BuildOnTheFly | lolcat
if [[ "$filename" == *.c ]]; then
	filename_without_extension="${filename%.c}"
	clang $filename -o $filename_without_extension
elif [[ "$filename" == *.cpp ]]; then
	filename_without_extension="${filename%.cpp}"
	clang++ $filename -o $filename_without_extension
elif [[ "$filename" == *.py ]]; then
	python $filename >Output
elif [[ "$filename" == *.sh ]]; then
	chmod +x $filename
	./$filename
elif [[ "$filename" == *.java ]]; then
	javac $filename
	filename_without_extension="${filename%.java}"
	java $filename_without_extension
elif [[ "$filename" == *.cs ]]; then
	mcs $filename
	filename_without_extension="${filename%.cs}"
	filename_with_exe_extension="${filename_without_extension}.exe"
	chmod +x $filename_with_exe_extension
	./$filename_with_exe_extension
else
	echo "Unknown file type or no file extension." | lolcat
fi

n=$(tput cols)
for ((i = 1; i <= n; i++)); do
	printf "-"
done
cat Output
